### ISSUE TITLE
Need FAILOVER example of code for golos

### ISSUE THREAD

**Issue by Nerossoul** [inertia186/radiator#11]
**it is steem code**
options = {
  ur: 'https://api.steemit.com',
  failover_urls: [
    'https://api.steemitstage.com',
    'https://gtg.steem.house:8090'
  ]
}
api = Radiator::Api.new(options)

Can you show how to use it for golos?
**"ur:"** <-- is it normal? may be **"url:"**

**Comment by inertia186** [comment]
Thanks.  I've updated the `README.md`.
