### ISSUE TITLE
endless loop

### ISSUE THREAD

**Issue by Nerossoul** [inertia186/radiator#12]
on sign transaction some times it gives this error
__________________
W, [2017-11-26T07:27:58.703001 #14419]  WARN -- : Failover reset, going back to https://api.golos.cf ...
E, [2017-11-26T07:27:58.939521 #14419] ERROR -- : Health check failure for https://ws.golos.io: #<OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=error: certificate verify failed>
---------------------------------
and it gives that text again and again in endless/ but if restart app it is work good until it give this error again/// Why it becomes endless loop?
![2017-11-26 07-42-33](https://user-images.githubusercontent.com/32826003/33236175-7aadf2ba-d27d-11e7-9ead-37b871f1f456.png)

**Comment by inertia186** [comment]
I don't believe this is a bug in radiator.  Rather, I believe this is caused by having too many files open in another part of the app.  Radiator is just trying to open the SSL certificate and the OS cannot allocate resources.

When this happens, try running this from the command line:

```bash
lsof | awk '{ print $2; }' | uniq -c | sort -rn | head
```

It will tell you which PID has the most files open.

**Comment by Nerossoul** [comment]
OK i will try this command///
But for the future is it possible to break this cycle and get control to my app back?

**Comment by Nerossoul** [comment]
so, i got this error again
lsof | awk '{ print $2; }' | uniq -c | sort -rn | head
gives me this
![2017-11-26 21-13-33](https://user-images.githubusercontent.com/32826003/33240905-0a1e26cc-d2f1-11e7-86ec-c6fcf4f07967.png)
it's told me that chromium_browse has the most files open
so i closed chromium
![2017-11-26 21-27-52](https://user-images.githubusercontent.com/32826003/33240932-530aa8c4-d2f1-11e7-91a7-d3f739cf677b.png)
and other PIDs was killed (all thats not ruby)
BUT ALL MY ACTIONS NOT BREAK ENDLESS LOOP
Please help!

**Comment by inertia186** [comment]
I have added a possible fix when your computer runs out of resources and cannot open files.  But it's better not to run out of resources (as of c933d62d268207d3330308d3c1870861b473b4f7).

I have another fix coming up that should help the garbage collector keep up in these situations, but I haven't fully tested it yet.

To update your app to the latest version of radiator, typically you can just use bundler:

```bash
bundle update
```

**Comment by Nerossoul** [comment]
Old problem is solved (i hope)
But I got many new error messages on version 0.3.14  
it is not trying to get **max_block_age** and sign transaction old wrong number block again and again///

#### ERROR
`10 assert_exception: Assert Exception
!check_max_block_age(_max_block_age):
    {}
    th_a  api.cpp:235 broadcast_transaction_with_callback

    {"call.method":"call","call.params":["network_broadcast_api","broadcast_transaction_synchronous",[{"expiration":"2017-11-28T15:24:27","ref_block_num":58160,"ref_block_prefix":859673073,"operations":[["vote",{"voter":"Someone","author":"sachuser","permlink":"somepermlink","weight":10000}]],"extensions":[],"signatures":["1c430a1somesignsture4e20a6601aa39ac7f3dc333953c52e2dc119c6c7f43b415b8ee24e5f598597dcb4c6bde65b9c59103734d4f19e9dd1be3"]}]]}
    th_a  websocket_api.cpp:124 on_message`

**Comment by Nerossoul** [comment]
SO, problem not solved///
![photo_2017-11-30_22-20-47](https://user-images.githubusercontent.com/32826003/33438241-d20bcf30-d61c-11e7-8b66-e090d1b6b089.jpg)

some of solutions here https://www.google.ru/search?q=SSL_connect+SYSCALL+returned%3D5+errno%3D0+state%3Derror%3A+certificate+verify+failed&oq=SSL_connect+SYSCALL+returned%3D5+errno%3D0+state%3Derror%3A+certificate+verify+failed&aqs=chrome..69i57.1239j0j7&client=ubuntu&sourceid=chrome&ie=UTF-8

i hope you can understand what to do.
help me.

**Comment by inertia186** [comment]
The problem is not in radiator.  Whatever you're doing requires more resources than you have.  Maybe you can troubleshoot it by turning off SSL Verify.

https://stackoverflow.com/questions/1113422/how-to-bypass-ssl-certificate-verification-in-open-uri

**Comment by Nerossoul** [comment]
It is not good idea to turn off SSL Verify
Can you give me control when this errors appears? just return response with this error/ i will decide how to get back resources...
something like that
```
 just count ssl errors >5 
response = error text
return response
```

**Comment by inertia186** [comment]
You're trying to troubleshoot radiator, but the problem is not in radiator.  I cannot troubleshoot your app.

**Comment by inertia186** [comment]
Another option for you is to avoid persistent HTTP by passing `persist: false`.

Doing this will impact performance because each API call will be a separate socket call.  All of the constructors accept `persist: false`., e.g.:

```ruby
api = Radiator::Api.new(chain: :golos, persist: false)
```

... or ...

```ruby
stream = Radiator::Stream.new(chain: :golos, persist: false)
```

... or ...

```ruby
tx = Radiator::Transaction.new(options.merge(persist: false, wif: wif))
```

**Comment by Nerossoul** [comment]
Great!!! it works
`persist: false ` changes situation
48 hours my errors count shows 0.
thx for your help!
