### ISSUE TITLE
Multi-transactions is it possible in radiator?

### ISSUE THREAD

**Issue by Nerossoul** [inertia186/radiator#19]
How to make multi-transaction like this?
If possible show code please.

golos.broadcast.send({
  extensions: [],
  operations: [
    ['transfer', {from:'user',to:'html',amount:'1.000 GBG',memo:'yo 1'}],
    ['transfer', {from:'user',to:'html',amount:'0.001 GBG',memo:'yo 2'}],
    ['transfer', {from:'user',to:'html',amount:'0.100 GBG',memo:'yo 3'}],
    ['transfer', {from:'user',to:'html',amount:'0.010 GBG',memo:'yo yo'}]
  ]}, [wif], console.log);

**Comment by inertia186** [comment]
```ruby
options = {chain: :golos}
tx = Radiator::Transaction.new(options.merge(wif: wif))

tx.operations << {type: :transfer, from: 'user', to: 'html', amount: '1.000 GBG', memo: 'yo 1'}
tx.operations << {type: :transfer, from: 'user', to: 'html', amount: '0.001 GBG', memo: 'yo 2'}
tx.operations << {type: :transfer, from: 'user', to: 'html', amount: '0.100 GBG', memo: 'yo 3'}
tx.operations << {type: :transfer, from: 'user', to: 'html', amount: '0.010 GBG', memo: 'yo yo'}

puts tx.process(true)
```
