### ISSUE TITLE
How to read posting bandwidth %

### ISSUE THREAD

**Issue by wakproductions** [inertia186/radiator#20]
Hi Anthony,

Terrific gem! I am using this to help content creators on other platforms establish a presence on Steemit! This is such a useful tool for the community.

I am trying to understand how the bandwidth works. On [steemd.com](https://steemd.com/@zolnareport), the bandwidth for my account has been fluctuating wildly in the %. Sometimes the figure is in the hundreds of Kb, and other times it says I have like 20Mb of bandwidth. I don't understand how it's calculating that.

When I do a query using the `get_account_bandwidth` API call, it gives me output like this:
```ruby
[114] pry(main)> a = api.get_account_bandwidth('zolnareport', 'post')
=> {"result"=>nil, "id"=>8}
[115] pry(main)> a = api.get_account_bandwidth('zolnareport', 'forum')
=> {"result"=>
  {"id"=>434010,
   "account"=>"zolnareport",
   "type"=>"forum",
   "average_bandwidth"=>"119606514378",
   "lifetime_bandwidth"=>"240016000000",
   "last_bandwidth_update"=>"2018-01-07T17:00:24"},
 "id"=>9}
[116] pry(main)> a = api.get_account_bandwidth('zolnareport', 'market')
=> {"result"=>nil, "id"=>10}
```

Could you please direct me to a resource that could explain how to calculate remaining bandwidth as a % so that I can set up my system to only post during times when I have available bandwidth?

**Comment by inertia186** [comment]
Hopefully, documentation for stuff like this will improve over time:

https://developers.steem.io/apidefinitions.html#apidefinitions-witness-api
https://developers.steem.io/apidefinitions.html#condenser_apiget_account_bandwidth
