### ISSUE TITLE
Unable to acquire database lock

### ISSUE THREAD

**Issue by recurator** [inertia186/radiator#24]
{:error_perser_exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :original_response=>{"jsonrpc"=>"2.0", "error"=>{"code"=>-32003, "message"=>"Unable to acquire database lock"}, "id"=>1070}}
./test.rb:45:in `block (2 levels) in <main>': undefined method `each' for nil:NilClass (NoMethodError)
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:173:in `block (2 levels) in operations'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:172:in `each'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:172:in `block in operations'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:201:in `block (2 levels) in transactions'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:196:in `each'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:196:in `each_with_index'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:196:in `block in transactions'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:298:in `block (4 levels) in blocks'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/api.rb:506:in `block in method_missing'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/api.rb:425:in `loop'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/api.rb:425:in `method_missing'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:284:in `block (3 levels) in blocks'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:263:in `each'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:263:in `block (2 levels) in blocks'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:231:in `catch'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:231:in `block in blocks'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:228:in `loop'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:228:in `blocks'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:192:in `transactions'
	from /home/jabre/.rvm/gems/ruby-2.4.1/gems/radiator-0.3.15/lib/radiator/stream.rb:137:in `operations'
	from ./test.rb:35:in `block in <main>'
	from ./testrb:33:in `loop'
	from ./test.rb:33:in `<main>'

**Comment by inertia186** [comment]
Corrently, `0.3` is unaware of this error.  I’m working on a version of `radiator` that is, in addition to appbase support in general.  You can try it out by switching to the `develop` branch or (as of this moment) using the current pre-release gem:

```ruby
gem ‘radiator’, ‘0.4.0pre3’
```

Or:

```bash
gem install radiator --pre
```
