### ISSUE TITLE
Golos change API can you fix it?

### ISSUE THREAD

**Issue by Nerossoul** [inertia186/radiator#26]
suport ws and http
https://github.com/GolosChain/golos/blob/v0.17.1RC1/share/golosd/config/config_witness.ini

webserver-http-endpoint = 0.0.0.0:8090
webserver-ws-endpoint = 0.0.0.0:8091

**Comment by inertia186** [comment]
I am not aware of a full public node on GOLOS that uses `http`.  But even if they did, they do not intend to implement AppBase (`radiator-0.4.x` or greater).  So moving forward, anyone who wants to use `radiator` will have to fork from `radiator-0.3.15`.

If you find a GOLOS node that runs `http`, use this in your `Gemfile`:

```ruby
gem 'radiator', '0.3.15'
```

**Comment by baybak** [comment]
public http Golos API node:
https://api.golos.blckchnd.com

**Comment by baybak** [comment]
GUI API
http://ropox.tools/steemjs/api
