### ISSUE TITLE
Radiator integration with a Rails App

### ISSUE THREAD

**Issue by jlebrijo** [inertia186/radiator#8]
Hi Anthony,

we are trying to integrate Radiator with our voting App https://crowdini.com.

We need to upload posts:

```ruby
tx = Radiator::Transaction.new(wif: wif)
```

But where can I get my WIF on my steemit account?

Once we have it, can I upload it with this code?:

```ruby
comment = {
    type: :post,
    parent_permlink: 'test',
    author: 'jlebrijo',
    permlink: 'something-unique',
    title: 'Radiator Can Post Comments!',
    body: 'Yep, this post was created by Radiator in `ruby`.',
    json_metadata: '',
    parent_author: ''
}

tx.operations << comment
tx.process(true)
```

Last question: What keys we need from our users to attach votes to these posts?

Thanks,
Juan

**Comment by inertia186** [comment]
Your account `wif` is in the permissions page, for example:

    https://steemit.com/@<my user name>/permissions

Both of those operations require posting private keys.
